### ISSUE TITLE
Neverending device migration

### ISSUE THREAD

**Issue by magpern** [gruijter/com.gruijter.zigbee2mqtt#4] opened 2023-09-19 06:07 UTC
This device a motion sensor, goes into a never ending "Device is migrating"
What do you need?

![Screenshot_20230919_080557_Homey](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/6589760/b304e4fe-dac5-44cf-9232-8f28a2151312)

**Comment by gruijter** [comment] 2023-09-19 08:53
pls send an app diagnostics report right 2 minutes after trying to add the device.

**Comment by magpern** [comment] 2023-09-19 17:45
If this is whay you asked for, this is what I got from the diagnostic report

732a0825-7aef-494e-92ec-81d458e72d3a

**Comment by gruijter** [comment] 2023-09-19 18:43
Yep got it. Will investigate prob this weekend.

**Comment by terafin** [comment] 2023-09-20 18:54
Adding another one here: f6fc5903-c461-4d91-8e7d-d940e44971ba

Thanks!

**Comment by Vitaliy-Yakovchuk** [comment] 2023-09-30 18:46
Getting the same error for Philips hue bulb

**Comment by gruijter** [comment] 2023-10-02 08:07
I cannot reproduce the issue. I suspect a restart of Homey, or only a restart of the app, should fix it.

**Comment by Vitaliy-Yakovchuk** [comment] 2023-10-02 16:21
Probably not related to the original issue, but there is indeed a bug Philips Hue bulbs, here is the fix:
https://github.com/gruijter/com.gruijter.zigbee2mqtt/pull/6

**Comment by Vitaliy-Yakovchuk** [comment] 2023-10-02 16:26
On the other hand that could be the same issue, if some device has duplicate in capabilities (not sure this is possible, not familiar with zigbee2mqtt), but if that is indeed the case, this could solve this issue with sensor as well.

**Comment by gruijter** [comment] 2023-10-02 16:37
Yes, that might very well cause the issue.
I guess I need to figure out why a z2m device can have the same capability multiple times. Am I missing some concept?

**Comment by Vitaliy-Yakovchuk** [comment] 2023-10-02 16:43
One more point: we (probably) could get capabilities from z2m in different order, this will also will lead to the issue, probably the safest code would be to remove duplicated and sort those capabilities in the same order all the time.

**Comment by gruijter** [comment] 2023-10-21 10:15
should be fixed in v2.1.1.

**Closed by gruijter** 2023-10-21 10:15 UTC
